// ─── Database Types ───────────────────────────────────────────────────────────
// This file will be auto-generated by the Supabase CLI once the schema is set up:
//   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > packages/supabase/src/database.types.ts
//
// Until then, this is a hand-written placeholder that matches the planned schema.
// Replace this file entirely once the Supabase project is created and schema is applied.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type MasteryLevel = 'new' | 'learning' | 'familiar' | 'mastered';
export type OpeningColor = 'white' | 'black';
export type OpeningDifficulty = 'beginner' | 'intermediate' | 'advanced';

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          user_id: string;
          display_name: string | null;
          avatar_url: string | null;
          skill_level: OpeningDifficulty | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          display_name?: string | null;
          avatar_url?: string | null;
          skill_level?: OpeningDifficulty | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          display_name?: string | null;
          avatar_url?: string | null;
          skill_level?: OpeningDifficulty | null;
          updated_at?: string;
        };
      };
      openings: {
        Row: {
          id: string;
          eco_code: string;
          name: string;
          color: OpeningColor;
          difficulty: OpeningDifficulty;
          description: string | null;
          tags: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          eco_code: string;
          name: string;
          color: OpeningColor;
          difficulty: OpeningDifficulty;
          description?: string | null;
          tags?: string[];
          created_at?: string;
        };
        Update: {
          eco_code?: string;
          name?: string;
          color?: OpeningColor;
          difficulty?: OpeningDifficulty;
          description?: string | null;
          tags?: string[];
        };
      };
      user_progress: {
        Row: {
          id: string;
          user_id: string;
          opening_id: string;
          times_practiced: number;
          success_rate: number;
          mastery_level: MasteryLevel;
          last_practiced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          opening_id: string;
          times_practiced?: number;
          success_rate?: number;
          mastery_level?: MasteryLevel;
          last_practiced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          times_practiced?: number;
          success_rate?: number;
          mastery_level?: MasteryLevel;
          last_practiced_at?: string | null;
          updated_at?: string;
        };
      };
      user_repertoires: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          updated_at?: string;
        };
      };
      repertoire_openings: {
        Row: {
          repertoire_id: string;
          opening_id: string;
          added_at: string;
        };
        Insert: {
          repertoire_id: string;
          opening_id: string;
          added_at?: string;
        };
        Update: never;
      };
      user_favorites: {
        Row: {
          user_id: string;
          opening_id: string;
          added_at: string;
        };
        Insert: {
          user_id: string;
          opening_id: string;
          added_at?: string;
        };
        Update: never;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      mastery_level: MasteryLevel;
      opening_color: OpeningColor;
      opening_difficulty: OpeningDifficulty;
    };
  };
}
