import type { OpeningColor, OpeningDifficulty } from '../types';

// ─── Raw Opening Definitions ──────────────────────────────────────────────────
// Only SAN move arrays. FENs are computed at runtime via chess.js.
// Generated by scripts/fetch-openings.ts + scripts/apply-openings.ts
// Source: ChessDB engine analysis (chessdb.cn)

export interface OpeningLineDefinition {
  id: string;
  name: string;
  description?: string;
  sans: string[];
}

export interface OpeningDefinition {
  id: string;
  ecoCode: string;
  name: string;
  color: OpeningColor;
  difficulty: OpeningDifficulty;
  description: string;
  mainLine: OpeningLineDefinition;
  variations: OpeningLineDefinition[];
  tags: string[];
}

export const OPENING_DEFINITIONS: OpeningDefinition[] = [
  // ─── Italian Game ────────────────────────────────────────────────
  {
    id: 'italian-game',
    ecoCode: 'C50',
    name: 'Italian Game',
    color: 'white',
    difficulty: 'beginner',
    description:
      'One of the oldest openings in chess. White develops rapidly, targets the center, and aims the bishop at the vulnerable f7 square.',
    mainLine: {
      id: 'italian-giuoco-piano',
      name: 'Giuoco Piano',
      description: 'Both sides develop naturally. White plans c3/d4 to challenge the center.',
      sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'c3', 'Nf6', 'd4', 'exd4', 'e5', 'd5', 'Bb5', 'Ne4', 'cxd4', 'Bb6', 'Nc3', 'O-O'],
    },
    variations: [
      {
        id: 'italian-pianissimo',
        name: 'Giuoco Pianissimo',
        description: 'White plays d3 for a slow, maneuvering game without the immediate c3/d4 pawn thrust.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'd3', 'Nf6', 'a4', 'O-O', 'O-O', 'a5', 'Nc3'],
      },
      {
        id: 'italian-two-knights',
        name: 'Two Knights Defense',
        description: 'Black counterattacks with Nf6 instead of mirroring the bishop.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'd3', 'Bc5', 'a4', 'O-O', 'O-O', 'a5', 'Nc3'],
      },
      {
        id: 'italian-fried-liver',
        name: 'Fried Liver Attack',
        description: 'White sacrifices a knight on f7 for a ferocious kingside attack.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5', 'd5', 'exd5', 'Nxd5', 'Nxf7'],
      },
      {
        id: 'italian-traxler',
        name: 'Traxler Counter-Attack',
        description: 'Black ignores the Ng5 threat and counter-attacks with Bc5, offering a piece.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5', 'Bc5', 'Bxf7+', 'Ke7'],
      },
      {
        id: 'italian-evans-gambit',
        name: 'Evans Gambit',
        description: 'White sacrifices a pawn on b4 for rapid development and a powerful attack.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'b4', 'Bxb4', 'c3', 'Be7', 'd4', 'exd4', 'cxd4', 'Nf6', 'd5', 'Na5', 'Bd3', 'c6'],
      },
      {
        id: 'italian-hungarian',
        name: 'Hungarian Defense',
        description: 'Black plays Be7 — solid and unpretentious, avoiding sharp theoretical battles.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Be7', 'd4', 'exd4', 'Nxd4', 'd6', 'Nc3', 'Nf6', 'O-O', 'O-O', 'Bf4', 'Ne5'],
      },
    ],
    tags: ['e4', 'open-game', 'classical', 'beginner-friendly'],
  },

  // ─── Ruy Lopez ───────────────────────────────────────────────────
  {
    id: 'ruy-lopez',
    ecoCode: 'C60',
    name: 'Ruy Lopez',
    color: 'white',
    difficulty: 'intermediate',
    description:
      'The most classic of all openings. White pressures the e5 pawn indirectly and aims for long-term positional dominance.',
    mainLine: {
      id: 'ruy-berlin',
      name: 'Berlin Defense',
      description: 'Rock-solid defense used by Magnus Carlsen to neutralize 1.e4. Leads to an endgame where Black holds comfortably.',
      sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nf6', 'O-O', 'Nxe4', 'd4', 'Nd6'],
    },
    variations: [
      {
        id: 'ruy-morphy-closed',
        name: 'Closed Variation',
        description: 'The main theoretical battleground of the Ruy Lopez. White builds a strong center with c3/d4.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Nc3', 'b5', 'Bb3', 'd6', 'a4', 'b4', 'Nd5', 'Na5'],
      },
      {
        id: 'ruy-marshall',
        name: 'Marshall Attack',
        description: 'Black sacrifices a pawn with d5 to launch a powerful kingside attack — one of the most daring gambits in chess.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Re1', 'b5', 'Bb3', 'O-O', 'c3', 'd5', 'exd5', 'Nxd5'],
      },
      {
        id: 'ruy-open',
        name: 'Open Variation',
        description: 'Black captures on e4 instead of castling — the sharpest and most active response.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Nxe4', 'd4', 'b5', 'Bb3', 'd5', 'dxe5', 'Be6', 'Be3', 'Be7'],
      },
      {
        id: 'ruy-exchange',
        name: 'Exchange Variation',
        description: 'White captures on c6 early, doubling Black\'s pawns for a structural edge.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Bxc6', 'dxc6', 'Nc3', 'f6', 'd4', 'exd4', 'Nxd4', 'c5', 'Nde2', 'Qxd1+', 'Nxd1', 'Be6'],
      },
      {
        id: 'ruy-schliemann',
        name: 'Schliemann Gambit',
        description: 'Black counter-attacks immediately with f5, sacrificing material for active play.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'f5', 'd3', 'fxe4', 'dxe4', 'Nf6', 'O-O', 'Bc5', 'Bxc6', 'bxc6'],
      },
      {
        id: 'ruy-steinitz',
        name: 'Steinitz Defense',
        description: 'Black supports e5 with d6 — solid but passive.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'd6', 'd4', 'exd4', 'O-O', 'Nf6', 'Nxd4', 'Bd7'],
      },
      {
        id: 'ruy-classical',
        name: 'Classical Defense',
        description: 'Black develops Bc5, mirroring White, leading to symmetrical tension.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Bc5', 'c3', 'Nf6', 'O-O', 'O-O', 'd4', 'Bb6'],
      },
    ],
    tags: ['e4', 'open-game', 'classical', 'positional'],
  },

  // ─── Scotch Game ─────────────────────────────────────────────────
  {
    id: 'scotch-game',
    ecoCode: 'C44',
    name: 'Scotch Game',
    color: 'white',
    difficulty: 'intermediate',
    description:
      'White immediately opens the center with d4 on move 3. Popularized by Kasparov in the 1990s as an alternative to the Ruy Lopez.',
    mainLine: {
      id: 'scotch-classical',
      name: 'Classical Variation',
      description: 'Black develops the bishop to c5 — the main theoretical response.',
      sans: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Bc5', 'Nb3', 'Bb6', 'a4', 'a5', 'Qe2', 'Nf6', 'Nc3', 'O-O', 'Be3', 'Bxe3'],
    },
    variations: [
      {
        id: 'scotch-mieses',
        name: 'Mieses Variation',
        description: 'Black plays Nf6 — the most popular modern response.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Nf6', 'Nxc6', 'bxc6', 'Bd3', 'd5', 'exd5', 'cxd5', 'O-O', 'Be7', 'b3', 'O-O'],
      },
      {
        id: 'scotch-four-knights',
        name: 'Four Knights Variation',
        description: 'Both sides develop knights, leading to a balanced position.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Nf6', 'Nc3', 'Bb4', 'Nxc6', 'bxc6', 'Bd3', 'd5', 'O-O', 'Bxc3', 'bxc3', 'dxe4'],
      },
      {
        id: 'scotch-gambit',
        name: 'Scotch Gambit',
        description: 'White plays Bc4 instead of recapturing, launching an aggressive gambit.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Bc4', 'Nf6', 'e5', 'd5', 'Bb5', 'Ne4', 'Nxd4', 'Bc5', 'O-O', 'O-O', 'Nxc6', 'bxc6'],
      },
      {
        id: 'scotch-steinitz',
        name: 'Steinitz Variation',
        description: 'Black plays Qh4 — an active but double-edged counter.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Qh4', 'Nc3', 'Bb4'],
      },
    ],
    tags: ['e4', 'open-game', 'classical', 'dynamic'],
  },

  // ─── Vienna Game ─────────────────────────────────────────────────
  {
    id: 'vienna-game',
    ecoCode: 'C25',
    name: 'Vienna Game',
    color: 'white',
    difficulty: 'beginner',
    description:
      'White develops Nc3 before committing the king\'s knight. Flexible — can lead to quiet positional or sharp gambit play.',
    mainLine: {
      id: 'vienna-main',
      name: 'Main Line',
      description: 'White plays Bc4 aiming for the center and f7.',
      sans: ['e4', 'e5', 'Nc3', 'Nc6', 'Bc4', 'Nf6', 'Nf3', 'Nxe4', 'Nxe4', 'd5', 'Bd3', 'dxe4', 'Bxe4', 'Nb4', 'a3', 'f5', 'Bxb7', 'Bxb7'],
    },
    variations: [
      {
        id: 'vienna-gambit',
        name: 'Vienna Gambit',
        description: 'White plays f4 to immediately challenge the center.',
        sans: ['e4', 'e5', 'Nc3', 'Nf6', 'f4', 'd5', 'fxe5', 'Nxe4', 'Qf3', 'Nc6', 'Bb5', 'Be6', 'Nge2', 'Qh4+', 'g3', 'Qe7', 'd4', 'Qd7'],
      },
      {
        id: 'vienna-mieses',
        name: 'Mieses Variation',
        description: 'White plays Nf3 for a quieter, more positional game.',
        sans: ['e4', 'e5', 'Nc3', 'Nc6', 'Nf3', 'Nf6', 'Bb5', 'Nd4', 'Bc4', 'Bc5', 'Nxe5', 'Qe7', 'Nd3', 'd5', 'Nxd5', 'Nxd5', 'Bxd5', 'Qg5'],
      },
      {
        id: 'vienna-frankenstein',
        name: 'Frankenstein-Dracula Variation',
        description: 'Black captures on e4 with the knight, leading to wild and complex complications.',
        sans: ['e4', 'e5', 'Nc3', 'Nf6', 'Bc4', 'Nxe4', 'Qh5', 'Nd6', 'Qxe5+', 'Qe7', 'Qxe7+', 'Bxe7', 'Be2', 'Nf5', 'Nf3', 'Nc6', 'Nd5', 'Bd8'],
      },
    ],
    tags: ['e4', 'open-game', 'flexible', 'beginner-friendly'],
  },

  // ─── Four Knights Game ───────────────────────────────────────────
  {
    id: 'four-knights-game',
    ecoCode: 'C46',
    name: 'Four Knights Game',
    color: 'white',
    difficulty: 'beginner',
    description:
      'Both sides develop all four knights before committing pawns. One of the most classical and symmetrical openings.',
    mainLine: {
      id: 'four-knights-spanish',
      name: 'Spanish Variation',
      description: 'White plays Bb5 — the main theoretical line, leading to rich middlegames.',
      sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Nc3', 'Nf6', 'Bb5', 'Nd4', 'Bc4', 'Bc5', 'Nxe5', 'Qe7', 'Nd3', 'd5', 'Nxd5', 'Nxd5', 'Bxd5', 'Qg5'],
    },
    variations: [
      {
        id: 'four-knights-italian',
        name: 'Italian Variation',
        description: 'White plays Bc4 — a quieter, classical approach.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Nc3', 'Nf6', 'Bc4', 'Nxe4', 'Nxe4', 'd5', 'Bd3', 'dxe4', 'Bxe4', 'Nb4', 'a3', 'f5', 'Bxb7', 'Bxb7'],
      },
      {
        id: 'four-knights-scotch',
        name: 'Scotch Variation',
        description: 'White plays d4, entering Scotch-like complications with four knights developed.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Nc3', 'Nf6', 'd4', 'exd4', 'Nxd4', 'Bb4', 'Nxc6', 'bxc6', 'Bd3', 'd5', 'O-O', 'Bxc3', 'bxc3', 'dxe4'],
      },
      {
        id: 'four-knights-halloween',
        name: 'Halloween Gambit',
        description: 'White sacrifices a knight on e5 for two pawns and a dangerous pawn roller.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'Nc3', 'Nf6', 'Nxe5', 'Nxe5', 'd4', 'Ng6'],
      },
    ],
    tags: ['e4', 'open-game', 'classical', 'beginner-friendly'],
  },

  // ─── King's Gambit ───────────────────────────────────────────────
  {
    id: 'kings-gambit',
    ecoCode: 'C30',
    name: 'King\'s Gambit',
    color: 'white',
    difficulty: 'intermediate',
    description:
      'One of the oldest and most aggressive openings. White sacrifices a pawn on move 2 for rapid development and a fierce kingside attack.',
    mainLine: {
      id: 'kga-accepted',
      name: 'King\'s Gambit Accepted',
      description: 'Black accepts the pawn — the sharpest and most principled reply.',
      sans: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'Be7', 'Bc4', 'Nf6', 'e5', 'Ne4', 'Bd5', 'Ng5', 'Nc3', 'd6', 'd4', 'Ne6', 'O-O', 'c6'],
    },
    variations: [
      {
        id: 'kga-fischer',
        name: 'Fischer Defense',
        description: 'Bobby Fischer\'s recommendation: d6 followed by g5, holding the pawn.',
        sans: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'd6', 'd4', 'g5', 'h4', 'g4', 'Ng1', 'Bh6', 'Nc3', 'c6', 'Nge2', 'Qf6', 'e5', 'dxe5'],
      },
      {
        id: 'kga-muzio',
        name: 'Muzio Gambit',
        description: 'White sacrifices the knight on f3 with O-O for a ferocious attack.',
        sans: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'g5', 'Bc4', 'g4', 'O-O', 'gxf3'],
      },
      {
        id: 'kga-bishops',
        name: 'Bishop\'s Gambit',
        description: 'White plays Bc4 instead of Nf3, a different attacking setup.',
        sans: ['e4', 'e5', 'f4', 'exf4', 'Bc4', 'Qh4+', 'Kf1', 'd6', 'd4', 'Be6'],
      },
      {
        id: 'kgd-falkbeer',
        name: 'Falkbeer Counter Gambit',
        description: 'Black sacrifices a pawn for immediate counterplay with d5.',
        sans: ['e4', 'e5', 'f4', 'd5', 'exd5', 'exf4', 'Nf3', 'Nf6', 'c4', 'Bd6', 'd4', 'O-O', 'Nc3', 'c5', 'Be2'],
      },
      {
        id: 'kgd-classical',
        name: 'King\'s Gambit Declined',
        description: 'Black declines with Bc5 — solid and avoids the sharp gambit lines.',
        sans: ['e4', 'e5', 'f4', 'Bc5', 'Nc3', 'd6', 'fxe5', 'dxe5', 'Qh5', 'Qd4', 'Qh4', 'Be7', 'Qg3', 'Nf6', 'Bb5+', 'c6', 'Be2', 'Nxe4'],
      },
    ],
    tags: ['e4', 'gambit', 'sharp', 'attacking', 'romantic'],
  },

  // ─── King's Indian Attack ────────────────────────────────────────
  {
    id: 'kings-indian-attack',
    ecoCode: 'A07',
    name: 'King\'s Indian Attack',
    color: 'white',
    difficulty: 'beginner',
    description:
      'White builds a solid fianchetto system with Nf3, g3, Bg2, d3. Can be used against almost any Black setup.',
    mainLine: {
      id: 'kia-vs-french',
      name: 'vs French Setup',
      description: 'Against 1...e6 2...d5 — White builds the KIA system and targets the kingside.',
      sans: ['e4', 'e6', 'd3', 'd5', 'Nd2', 'Nf6', 'Ngf3', 'Be7', 'g3', 'c5', 'Bg2', 'Nc6', 'O-O', 'O-O', 'Re1', 'h6'],
    },
    variations: [
      {
        id: 'kia-vs-sicilian',
        name: 'vs Sicilian Setup',
        description: 'Against 1...c5 — White fianchettoes and prepares a kingside attack.',
        sans: ['e4', 'c5', 'Nf3', 'e6', 'g3', 'Nc6', 'Bg2', 'd6', 'O-O', 'Nf6', 'd3', 'Be7', 'c4', 'Rb8', 'Nc3', 'O-O', 'd4', 'e5'],
      },
      {
        id: 'kia-main',
        name: 'Main Setup',
        description: 'White plays Nf3-g3-Bg2-O-O-d3-Nbd2 — a universal solid system.',
        sans: ['Nf3', 'd5', 'g3', 'Nf6', 'Bg2', 'e6', 'O-O', 'Be7', 'd3', 'O-O', 'Nbd2', 'a5', 'e4', 'a4', 'e5', 'Nfd7', 'Re1', 'c5'],
      },
    ],
    tags: ['system', 'solid', 'beginner-friendly', 'flexible'],
  },

  // ─── Sicilian Defense ────────────────────────────────────────────
  {
    id: 'sicilian-defense',
    ecoCode: 'B20',
    name: 'Sicilian Defense',
    color: 'black',
    difficulty: 'intermediate',
    description:
      'The most popular response to 1.e4. Black fights for the center asymmetrically, leading to rich, complex positions with winning chances for both sides.',
    mainLine: {
      id: 'sicilian-najdorf',
      name: 'Najdorf Variation',
      description: 'The most popular and theoretically rich Sicilian. Favored by Fischer and Kasparov.',
      sans: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Bc4', 'e6', 'a4', 'Nc6', 'Nxc6', 'bxc6', 'Bd3', 'Be7'],
    },
    variations: [
      {
        id: 'sicilian-dragon',
        name: 'Dragon Variation',
        description: 'Black fianchettoes the bishop for a powerful long diagonal battery.',
        sans: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'g6', 'Bc4', 'Bg7', 'O-O', 'Nc6', 'Bb5', 'Bd7'],
      },
      {
        id: 'sicilian-scheveningen',
        name: 'Scheveningen Variation',
        description: 'Black plays e6 — flexible and solid, allowing many setups.',
        sans: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e6', 'g4', 'h6', 'Rg1', 'Nc6', 'Be3', 'Be7', 'Qd2', 'Nxd4'],
      },
      {
        id: 'sicilian-classical',
        name: 'Classical Variation',
        description: 'Black plays Nc6 — solid and flexible development without early commitments.',
        sans: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e5', 'Ndb5', 'd6', 'Bg5', 'a6', 'Na3', 'b5', 'Nd5', 'Be7'],
      },
      {
        id: 'sicilian-sveshnikov',
        name: 'Sveshnikov Variation',
        description: 'Black plays e5 to challenge the center immediately, accepting a backward d-pawn for active piece play.',
        sans: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e5', 'Ndb5', 'd6', 'Bg5', 'a6', 'Na3', 'b5', 'Nd5', 'Be7'],
      },
      {
        id: 'sicilian-kan',
        name: 'Kan Variation',
        description: 'Black plays a6 — flexible, avoiding commitments and preparing e5 or d5.',
        sans: ['e4', 'c5', 'Nf3', 'e6', 'd4', 'cxd4', 'Nxd4', 'a6', 'h3', 'Nc6', 'Nxc6', 'bxc6', 'Bd3', 'd5', 'Nd2', 'Nf6', 'O-O', 'a5'],
      },
      {
        id: 'sicilian-taimanov',
        name: 'Taimanov Variation',
        description: 'Black plays Nc6 and e6 — solid and flexible, combining features of several systems.',
        sans: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'e6', 'Nc3', 'Nf6', 'Nxc6', 'bxc6', 'Bd3', 'd5', 'O-O', 'Be7', 'Bf4', 'O-O'],
      },
      {
        id: 'sicilian-accelerated-dragon',
        name: 'Accelerated Dragon',
        description: 'Black fianchettoes with g6 without playing d6 first, avoiding the Yugoslav Attack.',
        sans: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'g6', 'c4', 'Nf6', 'Nc3', 'd6', 'Be2', 'Nxd4', 'Qxd4', 'Bg7', 'O-O', 'O-O'],
      },
      {
        id: 'sicilian-alapin',
        name: 'Alapin Variation',
        description: 'White plays c3 to support a d4 pawn center — sidesteps heavy theory.',
        sans: ['e4', 'c5', 'c3', 'd5', 'exd5', 'Qxd5', 'Nf3', 'Nc6', 'Na3', 'Nf6', 'Bc4', 'Qd8', 'O-O', 'e6', 'Re1', 'Be7'],
      },
      {
        id: 'sicilian-grand-prix',
        name: 'Grand Prix Attack',
        description: 'White plays Nc3 and f4 for an aggressive kingside attack without playing d4.',
        sans: ['e4', 'c5', 'Nc3', 'Nc6', 'f4', 'd6', 'Nf3', 'g6', 'Bb5', 'Bd7', 'Bxc6', 'Bxc6', 'd4', 'cxd4', 'Nxd4', 'Qb6', 'Nxc6', 'bxc6'],
      },
      {
        id: 'sicilian-closed',
        name: 'Closed Sicilian',
        description: 'White plays g3 and Bg2 without d4 — a quiet system avoiding all Sicilian theory.',
        sans: ['e4', 'c5', 'Nc3', 'Nc6', 'g3', 'g6', 'Bg2', 'Bg7', 'Nge2', 'd6', 'O-O', 'h5', 'h3', 'h4'],
      },
    ],
    tags: ['e4', 'semi-open', 'dynamic', 'popular', 'sharp'],
  },

  // ─── French Defense ──────────────────────────────────────────────
  {
    id: 'french-defense',
    ecoCode: 'C00',
    name: 'French Defense',
    color: 'black',
    difficulty: 'intermediate',
    description:
      'Black builds a solid pawn chain and counterattacks the center. Leads to closed, strategic battles where Black is never clearly worse.',
    mainLine: {
      id: 'french-classical',
      name: 'Classical Variation',
      description: 'Black develops Nf6, directly challenging White\'s center. White typically plays e5.',
      sans: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Nf6', 'e5', 'Nfd7', 'f4', 'c5', 'Nf3', 'Nc6', 'a3', 'cxd4', 'Nb5', 'Bc5', 'b4', 'Be7'],
    },
    variations: [
      {
        id: 'french-winawer',
        name: 'Winawer Variation',
        description: 'Black pins the knight with Bb4 — creates imbalanced, double-edged positions.',
        sans: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Bb4', 'e5', 'c5', 'a3', 'Ba5', 'b4', 'cxd4', 'Nb5', 'Bc7', 'f4', 'Bd7', 'Nf3', 'Ne7'],
      },
      {
        id: 'french-tarrasch',
        name: 'Tarrasch Variation',
        description: 'White plays Nd2 instead of Nc3 — avoids the pin but loses some central influence.',
        sans: ['e4', 'e6', 'd4', 'd5', 'Nd2', 'Nf6', 'e5', 'Nfd7', 'Bd3', 'c5', 'c3', 'cxd4', 'cxd4', 'Nc6', 'Qg4', 'Qa5', 'Ne2', 'Qa4'],
      },
      {
        id: 'french-advance',
        name: 'Advance Variation',
        description: 'White advances e5 to gain space. Black immediately counterattacks with c5.',
        sans: ['e4', 'e6', 'd4', 'd5', 'e5', 'c5', 'c3', 'Nc6', 'Nf3', 'Qb6', 'Be2', 'cxd4', 'cxd4', 'Nh6', 'Bd3', 'Bd7', 'Bc2', 'Nf5'],
      },
      {
        id: 'french-exchange',
        name: 'Exchange Variation',
        description: 'White exchanges on d5 for a symmetrical, quieter game.',
        sans: ['e4', 'e6', 'd4', 'd5', 'exd5', 'exd5', 'Nf3', 'Bd6', 'c4', 'dxc4', 'Bxc4', 'Nf6', 'O-O', 'O-O', 'h3', 'Nc6'],
      },
      {
        id: 'french-rubinstein',
        name: 'Rubinstein Variation',
        description: 'Black exchanges on e4 — gives up the pawn center for easy development.',
        sans: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'Nd7', 'Nf3', 'Ngf6', 'Nxf6+', 'Nxf6', 'g3', 'b6', 'Bb5+', 'Bd7', 'a4', 'a6'],
      },
    ],
    tags: ['e4', 'semi-open', 'solid', 'strategic'],
  },

  // ─── Caro-Kann Defense ───────────────────────────────────────────
  {
    id: 'caro-kann',
    ecoCode: 'B15',
    name: 'Caro-Kann Defense',
    color: 'black',
    difficulty: 'intermediate',
    description:
      'A rock-solid response to 1.e4. Black establishes a strong pawn structure without locking in the light-squared bishop.',
    mainLine: {
      id: 'caro-classical',
      name: 'Classical Variation',
      description: 'Black exchanges on e4 and develops the bishop to f5 — the most principled response.',
      sans: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'Bf5', 'Ng3', 'Bg6', 'N1e2', 'Nf6', 'c3', 'Nbd7', 'h4', 'h6', 'Nf4', 'Bh7'],
    },
    variations: [
      {
        id: 'caro-advance',
        name: 'Advance Variation',
        description: 'White gains space with e5. Black develops the bishop outside the pawn chain before it closes.',
        sans: ['e4', 'c6', 'd4', 'd5', 'e5', 'Bf5', 'c3', 'e6', 'Nf3', 'c5', 'Bb5+', 'Nd7', 'O-O', 'a6', 'Be2', 'Ne7'],
      },
      {
        id: 'caro-panov',
        name: 'Panov-Botvinnik Attack',
        description: 'White plays c4 after the exchange — an aggressive attempt to unbalance the game.',
        sans: ['e4', 'c6', 'd4', 'd5', 'exd5', 'cxd5', 'c4', 'Nf6', 'Nc3', 'Nc6', 'Nf3', 'Bg4', 'cxd5', 'Nxd5', 'h3', 'Bxf3', 'Qxf3', 'e6'],
      },
      {
        id: 'caro-exchange',
        name: 'Exchange Variation',
        description: 'Symmetrical pawn structure. White looks for a small edge in the endgame.',
        sans: ['e4', 'c6', 'd4', 'd5', 'exd5', 'cxd5', 'Bd3', 'Nc6', 'c3', 'e5', 'dxe5', 'Nxe5', 'Qe2', 'Qe7', 'Bb5+', 'Bd7', 'Bf4', 'Nf3+'],
      },
      {
        id: 'caro-fantasy',
        name: 'Fantasy Variation',
        description: 'White plays f3 — an aggressive, non-standard try that leads to sharp play.',
        sans: ['e4', 'c6', 'd4', 'd5', 'f3', 'dxe4', 'fxe4', 'e5', 'Nf3', 'Bg4', 'c3', 'Nf6', 'Bc4', 'Bh5', 'Bg5', 'Nbd7', 'O-O', 'Bd6'],
      },
    ],
    tags: ['e4', 'semi-open', 'solid', 'positional'],
  },

  // ─── Petrov Defense ──────────────────────────────────────────────
  {
    id: 'petrov-defense',
    ecoCode: 'C42',
    name: 'Petrov Defense',
    color: 'black',
    difficulty: 'intermediate',
    description:
      'One of the most solid and drawish defenses to 1.e4. Black mirrors White\'s knight development and achieves quick equality.',
    mainLine: {
      id: 'petrov-classical',
      name: 'Classical Attack',
      description: 'White plays Nxe5 — the main line. Black must recapture correctly.',
      sans: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'd6', 'Nf3', 'Nxe4', 'd4', 'd5', 'Bd3', 'Bd6', 'O-O', 'O-O', 'c4', 'c6'],
    },
    variations: [
      {
        id: 'petrov-three-knights',
        name: 'Three Knights Variation',
        description: 'White develops Nc3, fighting for the center more aggressively.',
        sans: ['e4', 'e5', 'Nf3', 'Nf6', 'Nc3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Bb4', 'Nxc6', 'bxc6', 'Bd3', 'd5', 'O-O', 'Bxc3', 'bxc3', 'dxe4'],
      },
      {
        id: 'petrov-modern',
        name: 'Modern Attack',
        description: 'White plays d4 immediately — the most ambitious try for an advantage.',
        sans: ['e4', 'e5', 'Nf3', 'Nf6', 'd4', 'exd4', 'e5', 'Ne4', 'Qxd4', 'd5', 'exd6', 'Nxd6', 'Nc3', 'Nc6', 'Qa4', 'Bd7', 'h4', 'Ne5'],
      },
      {
        id: 'petrov-stafford',
        name: 'Stafford Gambit',
        description: 'Black counter-attacks with Nc6 instead of d6 — a dangerous gambit with many traps.',
        sans: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'Nc6', 'Nxc6', 'dxc6', 'd3', 'Bc5'],
      },
    ],
    tags: ['e4', 'open-game', 'solid', 'symmetrical'],
  },

  // ─── Scandinavian Defense ────────────────────────────────────────
  {
    id: 'scandinavian-defense',
    ecoCode: 'B01',
    name: 'Scandinavian Defense',
    color: 'black',
    difficulty: 'beginner',
    description:
      'Black immediately challenges White\'s e-pawn with d5 on move 1. One of the oldest recorded openings.',
    mainLine: {
      id: 'scand-main',
      name: 'Main Line',
      description: 'Black recaptures with the queen on d5 and repositions to a5 — the classical approach.',
      sans: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qa5', 'Nf3', 'Nf6', 'd4', 'Bf5', 'Ne5', 'c6', 'h4', 'Nbd7', 'Nc4', 'Qc7', 'Qf3', 'Bg4'],
    },
    variations: [
      {
        id: 'scand-modern',
        name: 'Modern Variation',
        description: 'Black retreats the queen to d6 — less exposed and more flexible than Qa5.',
        sans: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qd6', 'Nf3', 'Nf6', 'd4', 'c6', 'Ne5', 'g6', 'Bf4', 'Nh5', 'Be3', 'Nf6', 'Be2', 'Be6'],
      },
      {
        id: 'scand-mieses',
        name: 'Mieses-Kotrč Variation',
        description: 'Black develops Nf6 without recapturing immediately — accepts a pawn deficit for activity.',
        sans: ['e4', 'd5', 'exd5', 'Nf6', 'd4', 'Nxd5', 'Nf3', 'g6', 'c4', 'Nb6', 'Nc3', 'Bg7', 'Be2', 'O-O', 'h3', 'c5', 'd5'],
      },
      {
        id: 'scand-icelandic',
        name: 'Icelandic Gambit',
        description: 'Black plays e6, sacrificing the pawn back for rapid development after c4.',
        sans: ['e4', 'd5', 'exd5', 'Nf6', 'c4', 'e6', 'dxe6', 'Bxe6', 'Be2', 'Nc6', 'Nf3', 'Bc5', 'O-O', 'O-O', 'd3', 'Re8'],
      },
    ],
    tags: ['e4', 'semi-open', 'direct', 'beginner-friendly'],
  },

  // ─── Pirc Defense ────────────────────────────────────────────────
  {
    id: 'pirc-defense',
    ecoCode: 'B07',
    name: 'Pirc Defense',
    color: 'black',
    difficulty: 'intermediate',
    description:
      'Black allows White to build a large pawn center, then attacks it with pieces. A hypermodern defense.',
    mainLine: {
      id: 'pirc-classical',
      name: 'Classical System',
      description: 'White plays Be2 — solid development without overextending.',
      sans: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6', 'Nf3', 'Bg7', 'Be2', 'O-O', 'O-O', 'c5', 'd5', 'e6', 'Bc4', 'exd5', 'Nxd5', 'h6'],
    },
    variations: [
      {
        id: 'pirc-austrian',
        name: 'Austrian Attack',
        description: 'White plays f4 for an aggressive space-grabbing attack.',
        sans: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6', 'f4', 'Bg7', 'Nf3', 'O-O', 'Bd3', 'Nc6', 'O-O', 'e5', 'd5', 'Nd4', 'f5', 'c6'],
      },
      {
        id: 'pirc-150',
        name: '150 Attack',
        description: 'White plays Be3, Qd2, and O-O-O for a direct queenside castle and opposite-side attack.',
        sans: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6', 'Be3', 'Bg7', 'Qd2', 'O-O', 'O-O-O'],
      },
      {
        id: 'pirc-byrne',
        name: 'Byrne Variation',
        description: 'White plays Bg5 — an interesting alternative that pins the knight.',
        sans: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6', 'Bg5', 'Bg7', 'Qd2', 'Nc6'],
      },
    ],
    tags: ['e4', 'hypermodern', 'dynamic', 'counterattack'],
  },

  // ─── Modern Defense ──────────────────────────────────────────────
  {
    id: 'modern-defense',
    ecoCode: 'B06',
    name: 'Modern Defense',
    color: 'black',
    difficulty: 'intermediate',
    description:
      'Black plays g6 and Bg7 without playing d6 immediately — a flexible hypermodern setup.',
    mainLine: {
      id: 'modern-main',
      name: 'Main Line',
      description: 'White builds the center with d4 and Nc3, Black fianchettoes and waits.',
      sans: ['e4', 'g6', 'd4', 'Bg7', 'Nc3', 'd6', 'Nf3', 'Nf6', 'Be2', 'O-O', 'Be3', 'e5', 'dxe5', 'dxe5', 'Qxd8', 'Rxd8', 'Bc4', 'Nc6'],
    },
    variations: [
      {
        id: 'modern-averbakh',
        name: 'Averbakh System',
        description: 'White plays Be3 and Qd2 for a dangerous attacking setup.',
        sans: ['e4', 'g6', 'd4', 'Bg7', 'Nc3', 'd6', 'Be3', 'Nf6', 'Qd2', 'O-O'],
      },
      {
        id: 'modern-pseudo-dragon',
        name: 'Pseudo-Dragon Variation',
        description: 'Black plays c5 to challenge the center — transposes toward Sicilian Dragon ideas.',
        sans: ['e4', 'g6', 'd4', 'Bg7', 'Nc3', 'c5', 'd5', 'Bxc3+', 'bxc3', 'Qc7'],
      },
    ],
    tags: ['e4', 'hypermodern', 'flexible', 'dynamic'],
  },

  // ─── Latvian Gambit ──────────────────────────────────────────────
  {
    id: 'latvian-gambit',
    ecoCode: 'C40',
    name: 'Latvian Gambit',
    color: 'black',
    difficulty: 'advanced',
    description:
      'Black plays f5 on move 2 to counter-attack immediately. Objectively dubious but full of tactical traps.',
    mainLine: {
      id: 'latvian-accepted',
      name: 'Accepted',
      description: 'White accepts with Nxe5 — the main and most challenging response.',
      sans: ['e4', 'e5', 'Nf3', 'f5', 'Nxe5', 'Qf6', 'Nc4', 'fxe4', 'Nc3', 'Ne7'],
    },
    variations: [
      {
        id: 'latvian-greco',
        name: 'Greco Variation',
        description: 'White plays Bc4 — a safe and solid response.',
        sans: ['e4', 'e5', 'Nf3', 'f5', 'Bc4', 'fxe4', 'Nxe5', 'd5', 'Qh5+', 'g6', 'Nxg6', 'hxg6', 'Qxh8', 'Kf7', 'Be2', 'Bg7', 'Qh7'],
      },
      {
        id: 'latvian-fraser',
        name: 'Fraser Variation',
        description: 'White plays d4 — an aggressive central response.',
        sans: ['e4', 'e5', 'Nf3', 'f5', 'Nxe5', 'Qf6', 'Nc4', 'fxe4', 'd4', 'd5', 'Qh5+', 'Qf7', 'Qxf7+', 'Kxf7', 'Ne5+', 'Ke8', 'f3'],
      },
    ],
    tags: ['e4', 'gambit', 'sharp', 'trappy', 'romantic'],
  },

  // ─── Queen's Gambit ──────────────────────────────────────────────
  {
    id: 'queens-gambit',
    ecoCode: 'D06',
    name: 'Queen\'s Gambit',
    color: 'white',
    difficulty: 'intermediate',
    description:
      'White offers a pawn to seize central control. One of the oldest and most respected openings — used by world champions for over a century.',
    mainLine: {
      id: 'qgd-main',
      name: 'Queen\'s Gambit Declined',
      description: 'Black declines with e6 — the most principled and solid response.',
      sans: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'dxc4', 'e3', 'c5', 'd5', 'Be7', 'Bxf6', 'Bxf6', 'Bxc4', 'Bxc3+', 'bxc3', 'exd5'],
    },
    variations: [
      {
        id: 'slav-defense',
        name: 'Slav Defense',
        description: 'Black supports d5 with c6 — avoids locking in the light-squared bishop.',
        sans: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'dxc4', 'e3', 'b5', 'a4', 'b4', 'Nb1', 'Ba6', 'Nbd2', 'c3', 'bxc3', 'bxc3'],
      },
      {
        id: 'semi-slav',
        name: 'Semi-Slav Defense',
        description: 'Black combines c6 and e6 — one of the richest theoretical systems in chess.',
        sans: ['d4', 'd5', 'c4', 'c6', 'Nc3', 'Nf6', 'Nf3', 'e6', 'e3', 'Nbd7', 'Qc2', 'Bd6', 'cxd5', 'exd5', 'Bd3', 'O-O', 'O-O', 'Re8'],
      },
      {
        id: 'qga',
        name: 'Queen\'s Gambit Accepted',
        description: 'Black accepts the pawn with dxc4, fighting for equality with active play.',
        sans: ['d4', 'd5', 'c4', 'dxc4', 'Nf3', 'Nf6', 'e3', 'c5', 'Bxc4', 'a6', 'dxc5', 'Qxd1+', 'Kxd1', 'e6', 'b4', 'a5'],
      },
      {
        id: 'chigorin-defense',
        name: 'Chigorin Defense',
        description: 'Black develops Nc6 instead of a pawn — unconventional but rich in complications.',
        sans: ['d4', 'd5', 'c4', 'Nc6', 'Nf3', 'Bg4', 'cxd5', 'Bxf3', 'gxf3', 'Qxd5', 'e3', 'e5', 'Nc3', 'Bb4', 'Bd2', 'Bxc3', 'bxc3', 'Qd6'],
      },
      {
        id: 'cambridge-springs',
        name: 'Cambridge Springs Defense',
        description: 'Black plays Qa5 to create pressure on c3 and a2 — a classical trap-laden variation.',
        sans: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Nbd7', 'e3', 'c6', 'Nf3', 'Qa5', 'Bxf6', 'Nxf6', 'a3', 'Be7', 'b4', 'Qc7'],
      },
      {
        id: 'qgd-tartakower',
        name: 'Tartakower Variation',
        description: 'Black plays b6 to fianchetto the bishop — a flexible system popularized by Karpov.',
        sans: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Be7', 'Nf3', 'O-O', 'e3', 'b6', 'cxd5', 'Nxd5', 'Nxd5', 'exd5', 'Bxe7', 'Qxe7'],
      },
    ],
    tags: ['d4', 'closed-game', 'classical', 'positional'],
  },

  // ─── London System ───────────────────────────────────────────────
  {
    id: 'london-system',
    ecoCode: 'D02',
    name: 'London System',
    color: 'white',
    difficulty: 'beginner',
    description:
      'A simple, solid opening system White can use against almost anything. Develop the bishop to f4, support with e3, and build a strong center.',
    mainLine: {
      id: 'london-main',
      name: 'Main Line',
      description: 'The standard London setup against 1...d5 and 1...Nf6.',
      sans: ['d4', 'd5', 'Nf3', 'Nf6', 'Bf4', 'e6', 'e3', 'Bd6', 'Bxd6', 'Qxd6', 'c4', 'O-O', 'Be2', 'dxc4', 'Na3'],
    },
    variations: [
      {
        id: 'london-vs-kid',
        name: 'vs King\'s Indian Setup',
        description: 'Black fianchettoes — White maintains the same solid setup.',
        sans: ['d4', 'Nf6', 'Nf3', 'g6', 'Bf4', 'Bg7', 'e3', 'd6', 'Be2', 'O-O', 'O-O', 'Nh5', 'Bg5', 'h6', 'Bh4', 'c5', 'c3', 'g5'],
      },
      {
        id: 'london-vs-slav',
        name: 'vs Slav Setup',
        description: 'Black plays c6 early — White\'s London structure handles it comfortably.',
        sans: ['d4', 'd5', 'Nf3', 'Nf6', 'Bf4', 'c6', 'e3', 'Bf5', 'Nbd2', 'e6', 'c4', 'a5', 'Qb3', 'Qc8', 'Nh4', 'Be4', 'Be2', 'Nbd7'],
      },
      {
        id: 'london-barry',
        name: 'Barry Attack',
        description: 'White plays Nc3 to support an aggressive f3 and e4 pawn advance.',
        sans: ['d4', 'Nf6', 'Nf3', 'g6', 'Nc3', 'd5', 'Bf4', 'Bg7', 'e3', 'O-O', 'h3', 'c5', 'Be2', 'Ne4', 'O-O', 'Nc6', 'a4', 'a6'],
      },
    ],
    tags: ['d4', 'system', 'solid', 'beginner-friendly'],
  },

  // ─── Colle System ────────────────────────────────────────────────
  {
    id: 'colle-system',
    ecoCode: 'D05',
    name: 'Colle System',
    color: 'white',
    difficulty: 'beginner',
    description:
      'White builds a solid pyramid with d4, Nf3, e3, Bd3 and launches a kingside attack. Ideal for beginners who want a safe, consistent setup.',
    mainLine: {
      id: 'colle-koltanowski',
      name: 'Colle-Koltanowski',
      description: 'The standard Colle with c3 — White prepares a queenside break or kingside attack.',
      sans: ['d4', 'd5', 'Nf3', 'Nf6', 'e3', 'e6', 'Bd3', 'c5', 'c3', 'Nc6', 'Nbd2', 'Bd6', 'dxc5', 'Bxc5', 'b4', 'Bd6', 'O-O', 'O-O'],
    },
    variations: [
      {
        id: 'colle-zukertort',
        name: 'Colle-Zukertort',
        description: 'White plays b3 and Bb2 instead of c3 — a more dynamic bishop placement.',
        sans: ['d4', 'd5', 'Nf3', 'Nf6', 'e3', 'e6', 'Bd3', 'Nbd7', 'O-O', 'b3', 'Bb2', 'c5'],
      },
      {
        id: 'colle-vs-kid',
        name: 'vs King\'s Indian Setup',
        description: 'Black fianchettoes — White maintains the Colle pyramid.',
        sans: ['d4', 'Nf6', 'Nf3', 'g6', 'e3', 'Bg7', 'Bd3', 'd6', 'Nbd2', 'O-O', 'O-O', 'c5', 'c3', 'Nc6', 'e4', 'cxd4', 'cxd4', 'a5'],
      },
    ],
    tags: ['d4', 'system', 'solid', 'beginner-friendly', 'attacking'],
  },

  // ─── Catalan Opening ─────────────────────────────────────────────
  {
    id: 'catalan-opening',
    ecoCode: 'E00',
    name: 'Catalan Opening',
    color: 'white',
    difficulty: 'advanced',
    description:
      'White combines the Queen\'s Gambit with a kingside fianchetto. The long diagonal bishop and central pressure create lasting positional pressure.',
    mainLine: {
      id: 'catalan-open',
      name: 'Open Catalan',
      description: 'Black accepts with dxc4 — White regains it with long-term pressure.',
      sans: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'd5', 'g3', 'dxc4', 'Bg2', 'a6', 'Ne5', 'Bb4+', 'Nc3', 'Nd5', 'O-O', 'Nxc3', 'bxc3', 'Bxc3'],
    },
    variations: [
      {
        id: 'catalan-closed',
        name: 'Closed Catalan',
        description: 'Black keeps the center closed with Be7 — a solid, fortress-like setup.',
        sans: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'd5', 'g3', 'Be7', 'Bg2', 'O-O', 'O-O', 'dxc4', 'Qc2', 'a6', 'a4', 'Bd7', 'Bg5', 'Bc6'],
      },
      {
        id: 'catalan-anti',
        name: 'Anti-Catalan',
        description: 'Black plays c5 to immediately challenge the center before White fianchettoes.',
        sans: ['d4', 'd5', 'c4', 'e6', 'Nf3', 'Nf6', 'g3', 'c5', 'cxd5', 'exd5', 'Bg2', 'Nc6', 'Bg5', 'Be7', 'dxc5', 'Bxc5', 'O-O', 'O-O'],
      },
    ],
    tags: ['d4', 'closed-game', 'positional', 'advanced'],
  },

  // ─── Trompowsky Attack ───────────────────────────────────────────
  {
    id: 'trompowsky-attack',
    ecoCode: 'A45',
    name: 'Trompowsky Attack',
    color: 'white',
    difficulty: 'intermediate',
    description:
      'White pins the knight on f6 immediately with Bg5 — sidesteps all Indian Defense theory.',
    mainLine: {
      id: 'tromp-main',
      name: 'Main Line',
      description: 'Black plays Ne4, attacking the bishop — the most principled response.',
      sans: ['d4', 'Nf6', 'Bg5', 'Ne4', 'Bf4', 'c5', 'f3', 'Nf6', 'e4', 'cxd4', 'Qxd4', 'Nc6', 'Qd2', 'd5', 'e5', 'Nd7', 'Qxd5', 'e6'],
    },
    variations: [
      {
        id: 'tromp-d5',
        name: 'd5 Variation',
        description: 'Black plays d5 — solid, countering the center directly.',
        sans: ['d4', 'Nf6', 'Bg5', 'd5', 'Bxf6', 'exf6', 'e3', 'c5', 'Nf3', 'Nc6', 'Be2', 'Bd6', 'Nc3', 'Be6', 'dxc5', 'Bxc5', 'O-O', 'a6'],
      },
      {
        id: 'tromp-e6',
        name: 'e6 Variation',
        description: 'Black plays e6, ignoring the pin and developing solidly.',
        sans: ['d4', 'Nf6', 'Bg5', 'e6', 'e4', 'h6', 'Bxf6', 'Qxf6', 'c3', 'd5', 'Nd2', 'c5', 'Bb5+', 'Bd7', 'Bxd7+', 'Nxd7', 'exd5', 'cxd4'],
      },
    ],
    tags: ['d4', 'attacking', 'dynamic', 'system'],
  },

  // ─── King's Indian Defense ───────────────────────────────────────
  {
    id: 'kings-indian',
    ecoCode: 'E60',
    name: 'King\'s Indian Defense',
    color: 'black',
    difficulty: 'intermediate',
    description:
      'Black allows White to build a large center, then attacks it dynamically. One of the sharpest and most complex openings.',
    mainLine: {
      id: 'kid-classical',
      name: 'Classical Variation',
      description: 'White plays Be2 — the most popular main line response.',
      sans: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3', 'O-O', 'Be2', 'e5', 'd5', 'a5', 'h3', 'Na6', 'Bg5', 'Bd7'],
    },
    variations: [
      {
        id: 'kid-saemisch',
        name: 'Sämisch Variation',
        description: 'White plays f3 to support the center aggressively, weakening the kingside.',
        sans: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'f3', 'O-O', 'Be3', 'c5', 'dxc5', 'dxc5', 'Qxd8', 'Rxd8', 'Bxc5', 'Nc6'],
      },
      {
        id: 'kid-four-pawns',
        name: 'Four Pawns Attack',
        description: 'White grabs maximum center space with e4 and f4. Black must counterattack immediately.',
        sans: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'f4', 'O-O', 'Nf3', 'c5', 'Be2', 'cxd4', 'Nxd4', 'Nc6', 'Be3', 'Bg4'],
      },
      {
        id: 'kid-averbakh',
        name: 'Averbakh System',
        description: 'White plays Bg5 and Qd2 for a positional squeeze.',
        sans: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Be2', 'O-O', 'Bg5', 'c5', 'd5', 'e6', 'Qc1', 'Qa5', 'Bd2', 'Re8'],
      },
      {
        id: 'kid-petrosian',
        name: 'Petrosian System',
        description: 'White plays d5 to close the center and then attack on the queenside.',
        sans: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3', 'O-O', 'Be2', 'e5', 'd5', 'Ne7', 'Nd2'],
      },
      {
        id: 'kid-fianchetto',
        name: 'Fianchetto Variation',
        description: 'White fianchettoes the bishop — a quieter alternative to e4.',
        sans: ['d4', 'Nf6', 'c4', 'g6', 'Nf3', 'Bg7', 'g3', 'O-O', 'Bg2', 'd6', 'Nc3', 'c5', 'O-O', 'Nc6', 'dxc5', 'dxc5', 'Bf4', 'Nh5'],
      },
    ],
    tags: ['d4', 'indian-defense', 'dynamic', 'counterattack'],
  },

  // ─── Nimzo-Indian Defense ────────────────────────────────────────
  {
    id: 'nimzo-indian',
    ecoCode: 'E20',
    name: 'Nimzo-Indian Defense',
    color: 'black',
    difficulty: 'advanced',
    description:
      'Black pins the knight with Bb4 — one of the most respected defenses to 1.d4. Favored by Fischer and Kasparov.',
    mainLine: {
      id: 'nimzo-classical',
      name: 'Classical Variation',
      description: 'White plays Qc2 — the most popular modern response, avoiding the doubled pawns.',
      sans: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'Qc2', 'O-O', 'a3', 'Bxc3+', 'Qxc3', 'd5', 'Nf3', 'dxc4', 'Qxc4', 'b6', 'Bf4', 'Ba6'],
    },
    variations: [
      {
        id: 'nimzo-rubinstein',
        name: 'Rubinstein Variation',
        description: 'White plays e3 — solid and reliable.',
        sans: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'e3', 'O-O', 'Bd3', 'd5', 'Nf3', 'dxc4', 'Bxc4', 'c5', 'O-O', 'cxd4', 'exd4', 'Nc6'],
      },
      {
        id: 'nimzo-saemisch',
        name: 'Sämisch Variation',
        description: 'White plays a3 immediately, forcing Bxc3+ and doubling the pawns.',
        sans: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'a3', 'Bxc3+', 'bxc3', 'c5', 'e3', 'b6', 'Bd3', 'Bb7', 'f3', 'Nc6', 'Ne2', 'O-O'],
      },
      {
        id: 'nimzo-leningrad',
        name: 'Leningrad Variation',
        description: 'White plays Bg5 — an aggressive pin-based approach.',
        sans: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'Bg5', 'h6', 'Bh4', 'c5', 'd5', 'g5', 'Bg3', 'Bxc3+', 'bxc3', 'd6', 'e3', 'e5'],
      },
      {
        id: 'nimzo-three-knights',
        name: 'Three Knights Variation',
        description: 'White plays Nf3 for a flexible, developing move.',
        sans: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'Nf3', 'O-O', 'Bg5', 'c5', 'e3', 'cxd4', 'exd4', 'd5', 'cxd5', 'h6', 'Bxf6', 'Qxf6'],
      },
    ],
    tags: ['d4', 'indian-defense', 'classical', 'positional'],
  },

  // ─── Queen's Indian Defense ──────────────────────────────────────
  {
    id: 'queens-indian',
    ecoCode: 'E12',
    name: 'Queen\'s Indian Defense',
    color: 'black',
    difficulty: 'advanced',
    description:
      'Black plays b6 to fianchetto the bishop, controlling e4 without committing to d5 or e5.',
    mainLine: {
      id: 'qid-main',
      name: 'Main Line',
      description: 'White fianchettoes with g3 — the main theoretical battleground.',
      sans: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'g3', 'Bb7', 'Bg2', 'Be7', 'O-O', 'O-O', 'Nc3', 'd5', 'Ne5', 'Nbd7', 'cxd5', 'Nxd5'],
    },
    variations: [
      {
        id: 'qid-petrosian',
        name: 'Petrosian System',
        description: 'White plays a3 to prevent Bb4+ — a solid positional approach.',
        sans: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'a3', 'Bb7', 'Nc3', 'Ne4', 'Bd2', 'f5', 'e3', 'Be7', 'Qc2', 'O-O', 'Rd1', 'Bf6'],
      },
      {
        id: 'qid-miles',
        name: 'Miles Variation',
        description: 'Black plays Ba6 — an active approach, pressuring c4.',
        sans: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'g3', 'Ba6', 'b3', 'Bb4+', 'Bd2', 'Be7', 'Bg2', 'O-O', 'Ne5', 'd5', 'O-O'],
      },
      {
        id: 'qid-classical',
        name: 'Classical Variation',
        description: 'Black plays Bb4+ to gain the bishop pair.',
        sans: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'Nc3', 'Bb7', 'a3', 'd5', 'cxd5', 'Nxd5', 'Nxd5', 'Qxd5', 'Bf4', 'Bd6', 'Bxd6', 'cxd6'],
      },
    ],
    tags: ['d4', 'indian-defense', 'classical', 'positional'],
  },

  // ─── Grünfeld Defense ────────────────────────────────────────────
  {
    id: 'grunfeld-defense',
    ecoCode: 'D70',
    name: 'Grünfeld Defense',
    color: 'black',
    difficulty: 'advanced',
    description:
      'Black allows White to build a massive center with d4/c4/e4, then immediately attacks it. A hypermodern classic.',
    mainLine: {
      id: 'grunfeld-exchange',
      name: 'Exchange Variation',
      description: 'White grabs the center with e4 — the sharpest and most theoretical line.',
      sans: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'cxd5', 'Nxd5', 'e4', 'Nxc3', 'bxc3', 'Bg7', 'Nf3', 'c5', 'Bb5+', 'Nc6', 'O-O', 'cxd4'],
    },
    variations: [
      {
        id: 'grunfeld-russian',
        name: 'Russian System',
        description: 'White plays Qb3 — pressuring d5 and b7 simultaneously.',
        sans: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'Nf3', 'Bg7', 'Qb3', 'dxc4', 'Qxc4', 'O-O', 'e4', 'a6', 'Be2', 'b5', 'Qb3', 'c5'],
      },
      {
        id: 'grunfeld-three-knights',
        name: 'Three Knights Variation',
        description: 'White plays Nf3 — a quieter, more positional approach.',
        sans: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'Nf3', 'Bg7', 'Bg5', 'Ne4', 'cxd5', 'Nxg5', 'Nxg5', 'e6', 'Qd2', 'exd5', 'Qe3+', 'Kf8'],
      },
      {
        id: 'grunfeld-hungarian',
        name: 'Hungarian Variation',
        description: 'White plays Bg5 — pinning the knight before Black can fianchetto.',
        sans: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'Bg5', 'Ne4', 'Bh4', 'Nxc3', 'bxc3', 'dxc4', 'e3', 'Be6', 'Nf3', 'c5', 'Be2', 'Bg7'],
      },
    ],
    tags: ['d4', 'hypermodern', 'dynamic', 'counterattack'],
  },

  // ─── Dutch Defense ───────────────────────────────────────────────
  {
    id: 'dutch-defense',
    ecoCode: 'A80',
    name: 'Dutch Defense',
    color: 'black',
    difficulty: 'intermediate',
    description:
      'Black plays f5 to control e4. An aggressive and unbalancing response to 1.d4.',
    mainLine: {
      id: 'dutch-stonewall',
      name: 'Stonewall Variation',
      description: 'Black builds a solid pawn fortress with e6/d5/c6 — strong but passive.',
      sans: ['d4', 'f5', 'g3', 'Nf6', 'Bg2', 'e6', 'Nf3', 'd5', 'O-O', 'c6', 'c4', 'Bd6', 'c5', 'Bc7', 'b4', 'O-O', 'a4', 'Nbd7'],
    },
    variations: [
      {
        id: 'dutch-leningrad',
        name: 'Leningrad Variation',
        description: 'Black fianchettoes with g6 — creates an aggressive setup with long-term attacking chances.',
        sans: ['d4', 'f5', 'g3', 'Nf6', 'Bg2', 'g6', 'Nf3', 'Bg7', 'O-O', 'O-O', 'c4', 'd6', 'Nc3', 'c6', 'Qc2', 'Na6', 'Bg5', 'Qe8'],
      },
      {
        id: 'dutch-classical',
        name: 'Classical Variation',
        description: 'Black plays e6 and Be7 — solid and classical.',
        sans: ['d4', 'f5', 'g3', 'e6', 'Bg2', 'Nf6', 'Nf3', 'd5', 'O-O', 'Bd6', 'c4', 'O-O', 'Nc3', 'c6', 'Ne5', 'Nbd7', 'Bf4', 'Be7'],
      },
      {
        id: 'dutch-staunton',
        name: 'Staunton Gambit',
        description: 'White plays e4 immediately — an aggressive pawn sacrifice for rapid development.',
        sans: ['d4', 'f5', 'e4', 'fxe4', 'Nc3', 'Nf6', 'Bg5', 'g6', 'f3', 'd5', 'Qd2', 'Bg7', 'O-O-O', 'Nc6', 'h3', 'a6'],
      },
    ],
    tags: ['d4', 'attacking', 'unbalancing', 'counterattack'],
  },

  // ─── Benoni Defense ──────────────────────────────────────────────
  {
    id: 'benoni-defense',
    ecoCode: 'A61',
    name: 'Benoni Defense',
    color: 'black',
    difficulty: 'advanced',
    description:
      'Black plays c5 and allows White to advance d5, creating a dynamic pawn structure with long-term attacking chances.',
    mainLine: {
      id: 'benoni-modern',
      name: 'Modern Benoni',
      description: 'Black plays e6 to recapture — the main theoretical battleground.',
      sans: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e6', 'Nc3', 'exd5', 'cxd5', 'd6', 'Nf3', 'g6', 'Nd2', 'Bg7', 'e4', 'O-O', 'a4', 'Na6'],
    },
    variations: [
      {
        id: 'benoni-czech',
        name: 'Czech Benoni',
        description: 'Black plays e5 to completely block the position — a fortress-like setup.',
        sans: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e5', 'Nc3', 'd6', 'e4', 'Be7', 'Nf3'],
      },
      {
        id: 'benoni-taimanov',
        name: 'Taimanov Variation',
        description: 'White plays f4 — an aggressive pawn advance for an immediate attack.',
        sans: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e6', 'Nc3', 'exd5', 'cxd5', 'd6', 'f4', 'g6', 'Nf3', 'Bg7', 'e4', 'O-O', 'Bd3', 'Re8'],
      },
    ],
    tags: ['d4', 'dynamic', 'unbalancing', 'counterattack'],
  },

  // ─── Benko Gambit ────────────────────────────────────────────────
  {
    id: 'benko-gambit',
    ecoCode: 'A57',
    name: 'Benko Gambit',
    color: 'black',
    difficulty: 'intermediate',
    description:
      'Black sacrifices a pawn with b5 for long-term queenside pressure. Black gets excellent compensation in the endgame.',
    mainLine: {
      id: 'benko-accepted',
      name: 'Fully Accepted',
      description: 'White takes both pawns — Black gets powerful queenside pressure.',
      sans: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'b5', 'cxb5', 'a6', 'bxa6', 'Bxa6', 'Nc3', 'g6', 'e4', 'Bxf1', 'Kxf1', 'd6', 'g3', 'Bg7'],
    },
    variations: [
      {
        id: 'benko-half-accepted',
        name: 'Half Accepted',
        description: 'White accepts just the one pawn — a safer but still advantageous line.',
        sans: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'b5', 'cxb5', 'a6', 'b6', 'Qxb6', 'Nc3', 'd6', 'Nf3', 'g6', 'e4', 'Bg7', 'Be2', 'O-O'],
      },
      {
        id: 'benko-declined',
        name: 'Declined',
        description: 'White declines the gambit with e4 or f3 — avoids the pressure.',
        sans: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'b5', 'f3', 'e6', 'e4', 'exd5', 'exd5', 'bxc4', 'Bxc4', 'd6', 'Ne2', 'Nbd7', 'O-O', 'Be7'],
      },
    ],
    tags: ['d4', 'gambit', 'positional', 'queenside'],
  },

  // ─── Albin Counter-Gambit ────────────────────────────────────────
  {
    id: 'albin-counter-gambit',
    ecoCode: 'D08',
    name: 'Albin Counter-Gambit',
    color: 'black',
    difficulty: 'intermediate',
    description:
      'Black sacrifices a pawn with e5 to create dangerous counterplay. Contains the famous Lasker Trap.',
    mainLine: {
      id: 'albin-main',
      name: 'Main Line',
      description: 'White accepts and Black pushes d4 for strong central counterplay.',
      sans: ['d4', 'd5', 'c4', 'e5', 'dxe5', 'd4', 'Nf3', 'Nc6', 'g3', 'Nge7', 'Bg2', 'Ng6', 'O-O', 'Ngxe5', 'Nxe5', 'Nxe5'],
    },
    variations: [
      {
        id: 'albin-lasker',
        name: 'Lasker Trap',
        description: 'White tries e3 — Black unleashes Bb4+ and dxe3, a brilliant tactical sequence.',
        sans: ['d4', 'd5', 'c4', 'e5', 'dxe5', 'd4', 'e3', 'Bb4+', 'Bd2', 'dxe3', 'Bxb4', 'exf2+', 'Ke2', 'fxg1=N+'],
      },
    ],
    tags: ['d4', 'gambit', 'trappy', 'counterattack'],
  },

  // ─── Budapest Gambit ─────────────────────────────────────────────
  {
    id: 'budapest-gambit',
    ecoCode: 'A52',
    name: 'Budapest Gambit',
    color: 'black',
    difficulty: 'intermediate',
    description:
      'Black gambits a pawn with e5 after 2.c4 — a dangerous weapon full of traps for the unprepared.',
    mainLine: {
      id: 'budapest-alekhine',
      name: 'Alekhine Variation',
      description: 'Black plays Ng4 to recover the pawn with good piece activity.',
      sans: ['d4', 'Nf6', 'c4', 'e5', 'dxe5', 'Ng4', 'Nf3', 'Bc5', 'e3', 'Nc6', 'Nc3', 'O-O', 'Na4', 'Bb4+', 'Bd2'],
    },
    variations: [
      {
        id: 'budapest-fajarowicz',
        name: 'Fajarowicz Variation',
        description: 'Black plays Ne4 — an aggressive piece sacrifice for attacking chances.',
        sans: ['d4', 'Nf6', 'c4', 'e5', 'dxe5', 'Ne4', 'a3', 'd6', 'exd6', 'Bxd6', 'Nd2', 'Bf5', 'Nxe4', 'Bxe4', 'c5', 'Bxc5', 'Qxd8+', 'Kxd8'],
      },
      {
        id: 'budapest-declined',
        name: 'Declined',
        description: 'White declines with d5 — avoiding the gambit complications.',
        sans: ['d4', 'Nf6', 'c4', 'e5', 'd5', 'Bc5', 'Nc3', 'O-O', 'e4', 'd6', 'h3', 'Bb4', 'Qc2', 'Bxc3+', 'bxc3', 'Nbd7', 'Ne2', 'Nc5'],
      },
    ],
    tags: ['d4', 'gambit', 'trappy', 'counterattack'],
  },

  // ─── English Opening ─────────────────────────────────────────────
  {
    id: 'english-opening',
    ecoCode: 'A10',
    name: 'English Opening',
    color: 'white',
    difficulty: 'advanced',
    description:
      'White plays c4 to control d5 without committing a central pawn. One of the most flexible openings, often transposing into d4 lines.',
    mainLine: {
      id: 'english-symmetrical',
      name: 'Symmetrical Variation',
      description: 'Black mirrors with c5 — leads to rich, maneuvering battles.',
      sans: ['c4', 'c5', 'Nf3', 'Nf6', 'Nc3', 'Nc6', 'g3', 'g6', 'Bg2', 'Bg7', 'O-O', 'O-O', 'd4', 'cxd4', 'Nxd4', 'd6', 'Nc2', 'Be6'],
    },
    variations: [
      {
        id: 'english-reversed-sicilian',
        name: 'Reversed Sicilian',
        description: 'Black plays e5 — White gets a Sicilian with colors reversed.',
        sans: ['c4', 'e5', 'Nc3', 'Nf6', 'Nf3', 'Nc6', 'g3', 'd5', 'cxd5', 'Nxd5', 'Bg2', 'Nxc3', 'bxc3', 'Bd6', 'O-O', 'O-O', 'd4', 'Re8'],
      },
      {
        id: 'english-kings-indian',
        name: 'King\'s Indian Formation',
        description: 'Black sets up a King\'s Indian structure — sharp counterattacking play.',
        sans: ['c4', 'Nf6', 'Nc3', 'g6', 'g3', 'Bg7', 'Bg2', 'O-O', 'd3', 'd6', 'Nf3', 'c5', 'O-O', 'Nc6', 'Rb1', 'a6', 'a3', 'Rb8'],
      },
      {
        id: 'english-four-knights',
        name: 'Four Knights Variation',
        description: 'Both sides develop knights — a symmetrical battle for center control.',
        sans: ['c4', 'c5', 'Nf3', 'Nc6', 'Nc3', 'Nf6', 'd4', 'cxd4', 'Nxd4', 'e6', 'g3', 'Qb6', 'Nb3', 'Ne5', 'e4', 'Bb4', 'Qe2', 'd6'],
      },
    ],
    tags: ['c4', 'flank', 'positional', 'advanced'],
  },

  // ─── Réti Opening ────────────────────────────────────────────────
  {
    id: 'reti-opening',
    ecoCode: 'A04',
    name: 'Réti Opening',
    color: 'white',
    difficulty: 'advanced',
    description:
      'White plays Nf3, delaying d4 to keep flexibility. A hypermodern system where White attacks d5 from a distance.',
    mainLine: {
      id: 'reti-main',
      name: 'Réti Gambit',
      description: 'White plays c4, attacking d5 in hypermodern fashion.',
      sans: ['Nf3', 'd5', 'c4', 'd4', 'b4', 'f6', 'e3', 'e5', 'c5', 'a5', 'Qa4+', 'Bd7', 'b5', 'Bxc5', 'Bc4', 'Ne7', 'exd4', 'exd4'],
    },
    variations: [
      {
        id: 'reti-kia',
        name: 'King\'s Indian Attack',
        description: 'White fianchettoes with g3 and Bg2 — a universal attacking setup.',
        sans: ['Nf3', 'd5', 'g3', 'Nf6', 'Bg2', 'e6', 'O-O', 'Be7', 'd3', 'O-O', 'Nbd2', 'c5', 'e4', 'Nc6', 'Re1', 'h6', 'c3', 'dxe4'],
      },
      {
        id: 'reti-anglo-grunfeld',
        name: 'Anglo-Grünfeld',
        description: 'Black plays g6 and d5 — a Grünfeld-like structure from a Réti move order.',
        sans: ['Nf3', 'Nf6', 'c4', 'g6', 'g3', 'd5', 'cxd5', 'Nxd5', 'Bg2', 'Bg7', 'O-O', 'c5', 'd4', 'cxd4', 'Nxd4', 'O-O', 'Nc3', 'Nxc3'],
      },
    ],
    tags: ['Nf3', 'hypermodern', 'positional', 'flexible'],
  },

  // ─── Danish Gambit ───────────────────────────────────────────────
  {
    id: 'danish-gambit',
    ecoCode: 'C21',
    name: 'Danish Gambit',
    color: 'white',
    difficulty: 'intermediate',
    description:
      'White sacrifices two pawns for blistering development and a powerful attack. One of the most aggressive openings in chess.',
    mainLine: {
      id: 'danish-accepted',
      name: 'Accepted',
      description: 'Black takes both pawns — White gets overwhelming development and attacking chances.',
      sans: ['e4', 'e5', 'd4', 'exd4', 'c3', 'dxc3', 'Bc4', 'cxb2', 'Bxb2', 'Nf6', 'e5', 'Bb4+', 'Bc3', 'Qe7', 'Qe2', 'Ng8', 'a3', 'Bxc3+'],
    },
    variations: [
      {
        id: 'danish-schlechter',
        name: 'Schlechter Defense',
        description: 'Black declines with d5 — the best defensive try.',
        sans: ['e4', 'e5', 'd4', 'exd4', 'c3', 'd5', 'exd5', 'Qxd5', 'cxd4', 'Nc6', 'Nf3', 'Bb4+', 'Nc3', 'Bg4', 'Be2', 'Bxf3', 'Bxf3', 'Qc4'],
      },
      {
        id: 'danish-declined',
        name: 'Declined — d5',
        description: 'Black plays d5 to return the pawn with a solid position.',
        sans: ['e4', 'e5', 'd4', 'exd4', 'c3', 'dxc3', 'Nxc3', 'Nc6', 'Nf3', 'Bb4', 'Bc4', 'Nf6', 'e5', 'd5', 'exf6', 'dxc4', 'Qxd8+', 'Nxd8'],
      },
    ],
    tags: ['e4', 'gambit', 'attacking', 'sharp', 'romantic'],
  },

  // ─── Göring Gambit ───────────────────────────────────────────────
  {
    id: 'goring-gambit',
    ecoCode: 'C44',
    name: 'Göring Gambit',
    color: 'white',
    difficulty: 'intermediate',
    description:
      'White plays c3 after the Scotch — offering a pawn for rapid development and active piece play.',
    mainLine: {
      id: 'goring-accepted',
      name: 'Accepted',
      description: 'Black accepts both pawns — White launches a powerful attack with Bc4.',
      sans: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'c3', 'dxc3', 'Bc4', 'cxb2', 'Bxb2', 'd6', 'Nbd2', 'Be6', 'Rc1', 'Bxc4', 'Nxc4', 'Nf6'],
    },
    variations: [
      {
        id: 'goring-declined',
        name: 'Declined — d5',
        description: 'Black declines with d5 — the solid response.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'c3', 'd5', 'exd5', 'Qxd5', 'cxd4', 'Nc6'],
      },
      {
        id: 'goring-one-pawn',
        name: 'One Pawn Accepted',
        description: 'Black takes one pawn but declines the second — a cautious approach.',
        sans: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'c3', 'dxc3', 'Nxc3', 'Nf6', 'e5', 'Ng4', 'Qe2', 'd6', 'exd6+', 'Be6', 'dxc7', 'Qxc7'],
      },
    ],
    tags: ['e4', 'gambit', 'attacking', 'sharp'],
  },

  // ─── Smith-Morra Gambit ──────────────────────────────────────────
  {
    id: 'smith-morra-gambit',
    ecoCode: 'B21',
    name: 'Smith-Morra Gambit',
    color: 'white',
    difficulty: 'intermediate',
    description:
      'White sacrifices a pawn against the Sicilian for rapid development and open lines. A dangerous weapon at club level.',
    mainLine: {
      id: 'smg-accepted',
      name: 'Accepted',
      description: 'Black accepts — White gets enormous development advantage.',
      sans: ['e4', 'c5', 'd4', 'cxd4', 'c3', 'dxc3', 'Nxc3', 'Nc6', 'Nf3', 'd6', 'Bc4', 'e6', 'O-O', 'Nf6', 'Qe2', 'Bd7'],
    },
    variations: [
      {
        id: 'smg-declined-nf6',
        name: 'Declined — Nf6',
        description: 'Black declines with Nf6, avoiding the gambit.',
        sans: ['e4', 'c5', 'd4', 'cxd4', 'c3', 'Nf6', 'e5', 'Nd5', 'cxd4', 'Nc6', 'Nf3', 'd6', 'Nc3', 'dxe5', 'dxe5', 'Nxc3', 'Qxd8+', 'Nxd8'],
      },
      {
        id: 'smg-declined-e3',
        name: 'Declined — e3',
        description: 'Black declines with e3 — an unusual but solid response.',
        sans: ['e4', 'c5', 'd4', 'cxd4', 'c3', 'e6', 'cxd4', 'd5', 'exd5', 'exd5', 'Nf3', 'Bd6', 'Nc3', 'Ne7', 'Bd3', 'Nbc6', 'O-O', 'O-O'],
      },
    ],
    tags: ['e4', 'gambit', 'attacking', 'sharp', 'anti-sicilian'],
  },

  // ─── Blackmar-Diemer Gambit ──────────────────────────────────────
  {
    id: 'blackmar-diemer-gambit',
    ecoCode: 'D00',
    name: 'Blackmar-Diemer Gambit',
    color: 'white',
    difficulty: 'intermediate',
    description:
      'White sacrifices a pawn with e4 and f3 against the Slav pawn structure for wild attacking play.',
    mainLine: {
      id: 'bdg-teichmann',
      name: 'Teichmann Defense',
      description: 'Black plays Bg4 to pin the knight — the most popular defensive try.',
      sans: ['d4', 'd5', 'e4', 'dxe4', 'Nc3', 'Nf6', 'f3', 'exf3', 'Nxf3', 'Bg4', 'h3', 'Bxf3', 'Qxf3', 'c6', 'g4', 'e6', 'g5', 'Nd5'],
    },
    variations: [
      {
        id: 'bdg-euwe',
        name: 'Euwe Defense',
        description: 'Black plays e6 — solid and classical.',
        sans: ['d4', 'd5', 'e4', 'dxe4', 'Nc3', 'Nf6', 'f3', 'exf3', 'Nxf3', 'e6', 'Bg5', 'Be7', 'Bd3', 'Na6', 'Qe2', 'Nb4', 'Bc4', 'O-O'],
      },
      {
        id: 'bdg-lemberger',
        name: 'Lemberger Counter-Gambit',
        description: 'Black counter-gambles with e5 — the sharpest response.',
        sans: ['d4', 'd5', 'e4', 'dxe4', 'Nc3', 'e5', 'dxe5', 'Qxd1+', 'Nxd1', 'Nc6', 'f3', 'Bf5', 'Ne3', 'Bg6', 'f4', 'Bc5', 'Ne2', 'O-O-O'],
      },
    ],
    tags: ['d4', 'gambit', 'attacking', 'sharp'],
  },

  // ─── Bird's Opening ──────────────────────────────────────────────
  {
    id: 'birds-opening',
    ecoCode: 'A02',
    name: 'Bird\'s Opening',
    color: 'white',
    difficulty: 'beginner',
    description:
      'White plays f4 — a flank opening controlling e5 and preparing a Dutch-style attack.',
    mainLine: {
      id: 'birds-main',
      name: 'Main Line',
      description: 'White builds a Dutch-like structure with Nf3 and d3.',
      sans: ['f4', 'd5', 'Nf3', 'Nf6', 'e3', 'g6', 'Be2', 'Bg7', 'O-O', 'O-O', 'd3', 'b6', 'Ne5', 'Bb7', 'b3', 'Ne8', 'Bb2', 'Nd6'],
    },
    variations: [
      {
        id: 'birds-from-gambit',
        name: 'From Gambit',
        description: 'Black sacrifices a pawn with e5 — a dangerous counter-attack against Bird\'s.',
        sans: ['f4', 'e5', 'fxe5', 'd6', 'exd6', 'Bxd6', 'Nf3', 'g5', 'd4', 'g4', 'Ne5', 'Bxe5', 'dxe5', 'Qxd1+', 'Kxd1', 'Nc6', 'Bf4', 'Be6'],
      },
      {
        id: 'birds-leningrad',
        name: 'Leningrad Variation',
        description: 'White plays Nf3 and g3 — a quieter fianchetto setup.',
        sans: ['f4', 'd5', 'Nf3', 'Nf6', 'g3', 'g6', 'Bg2', 'Bg7', 'O-O', 'O-O', 'd3', 'c5', 'Ne5', 'Qb6', 'c4', 'Be6', 'Nc3', 'dxc4'],
      },
    ],
    tags: ['f4', 'flank', 'attacking', 'offbeat'],
  }
];
