/**
 * scripts/apply-openings.ts
 *
 * Reads scripts/output/openings-fetched.json and overwrites
 * packages/core/src/openings/data.ts with the engine-fetched move sequences.
 *
 * Usage:
 *   npx tsx scripts/apply-openings.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

interface FetchedLine {
  id: string;
  name: string;
  description?: string;
  sans: string[];
}

interface FetchedOpening {
  id: string;
  ecoCode: string;
  name: string;
  color: string;
  difficulty: string;
  description: string;
  tags: string[];
  lines: FetchedLine[];
}

function formatSans(sans: string[]): string {
  return sans.map(s => `'${s}'`).join(', ');
}

function esc(s: string): string {
  return s.replace(/'/g, "\\'");
}

function formatLine(line: FetchedLine, indent: string): string {
  const desc = line.description ? `\n${indent}  description: '${esc(line.description)}',` : '';
  return `{
${indent}  id: '${line.id}',
${indent}  name: '${esc(line.name)}',${desc}
${indent}  sans: [${formatSans(line.sans)}],
${indent}}`;
}

function generate(openings: FetchedOpening[]): string {
  const blocks = openings.map(o => {
    const [mainLine, ...variations] = o.lines;
    const mainDesc = mainLine.description
      ? `\n      description: '${esc(mainLine.description)}',`
      : '';

    const variationsBlock = variations.length === 0
      ? '[]'
      : `[\n      ${variations.map(v => formatLine(v, '      ')).join(',\n      ')},\n    ]`;

    const tags = o.tags.map(t => `'${t}'`).join(', ');

    return `  // ─── ${o.name} ${'─'.repeat(Math.max(0, 60 - o.name.length))}
  {
    id: '${o.id}',
    ecoCode: '${o.ecoCode}',
    name: '${esc(o.name)}',
    color: '${o.color}',
    difficulty: '${o.difficulty}',
    description:
      '${esc(o.description)}',
    mainLine: {
      id: '${mainLine.id}',
      name: '${esc(mainLine.name)}',${mainDesc}
      sans: [${formatSans(mainLine.sans)}],
    },
    variations: ${variationsBlock},
    tags: [${tags}],
  }`;
  });

  return `import type { OpeningColor, OpeningDifficulty } from '../types';

// ─── Raw Opening Definitions ──────────────────────────────────────────────────
// Only SAN move arrays. FENs are computed at runtime via chess.js.
// Generated by scripts/fetch-openings.ts + scripts/apply-openings.ts
// Source: ChessDB engine analysis (chessdb.cn)

export interface OpeningLineDefinition {
  id: string;
  name: string;
  description?: string;
  sans: string[];
}

export interface OpeningDefinition {
  id: string;
  ecoCode: string;
  name: string;
  color: OpeningColor;
  difficulty: OpeningDifficulty;
  description: string;
  mainLine: OpeningLineDefinition;
  variations: OpeningLineDefinition[];
  tags: string[];
}

export const OPENING_DEFINITIONS: OpeningDefinition[] = [
${blocks.join(',\n\n')}
];
`;
}

const inputPath = path.join(__dirname, 'output', 'openings-fetched.json');
const outputPath = path.join(__dirname, '..', 'packages', 'core', 'src', 'openings', 'data.ts');

const openings: FetchedOpening[] = JSON.parse(fs.readFileSync(inputPath, 'utf-8'));
const output = generate(openings);

fs.writeFileSync(outputPath, output);
console.log(`✓ Written to ${outputPath}`);
console.log(`  ${openings.length} openings, ${openings.reduce((n, o) => n + o.lines.length, 0)} lines total`);
